core/urls.py
from django.urls import path
from . import views

urlpatterns = [ 

	path('', views.index, name='index'),
	path('login', views.login, name='login'),
	path('signup', views.signup, name='signup'),
	path('logout', views.logout, name='logout'),
    path('movie/<str:pk>/', views.movie, name='movie'),
    path('genre/<str:pk>/', views.genre, name='genre'),
    path('my-list', views.my_list, name='my-list'),
    path('add-to-list', views.add_to_list, name='add-to-list'),
    path('search', views.search, name='search'),

] 

netflix/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls'))
]

urlpatterns = urlpatterns+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models
import uuid
from django.conf import settings

# Create your models here.
class Movie(models.Model):

    GENRE_CHOICES = [
        ('action', 'Action'),
        ('comedy', 'Comedy'),
        ('drama', 'Drama'),
        ('horror', 'Horror'),
        ('romance', 'Romance'),
        ('science_fiction', 'Science Fiction'),
        ('fantasy', 'Fantasy'),
    ]

    uu_id = models.UUIDField(default=uuid.uuid4)
    title = models.CharField(max_length=255)
    description = models.TextField()
    release_date = models.DateField()
    genre = models.CharField(max_length=100, choices=GENRE_CHOICES)
    length = models.PositiveIntegerField()
    image_card = models.ImageField(upload_to='movie_images/')
    image_cover = models.ImageField(upload_to='movie_images/')
    video = models.FileField(upload_to='movie_videos/')
    movie_views = models.IntegerField(default=0)

    def __str__(self):
        return self.title
    
    
class MovieList(models.Model):
    owner_user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)



    

core/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User, auth
from django.contrib import messages
from .models import Movie, MovieList
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.shortcuts import get_object_or_404
import re

# Create your views here.
@login_required(login_url='login')
def index(request):
    movies = Movie.objects.all()
    featured_movie = movies[len(movies)-1]

    context = {
        'movies': movies,
        'featured_movie': featured_movie,
    }
    return render(request, 'index.html', context)



@login_required(login_url='login')
def movie(request, pk):
    movie_uuid = pk
    movie_details = Movie.objects.get(uu_id=movie_uuid)

    context = {
        'movie_details': movie_details
    }

    return render(request, 'movie.html', context)



@login_required(login_url='login')
def genre(request, pk):
    movie_genre = pk
    movies = Movie.objects.filter(genre=movie_genre)

    context = {
        'movies': movies,
        'movie_genre': movie_genre,
    }
    return render(request, 'genre.html', context)

@login_required(login_url='login')
def search(request):
    if request.method == 'POST':
        search_term = request.POST['search_term']
        movies = Movie.objects.filter(title__icontains=search_term)

        context = {
            'movies': movies,
            'search_term': search_term,
        }
        return render(request, 'search.html', context)
    else:
        return redirect('/')





def login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        user = auth.authenticate(username=username, password=password)

        if user is not None:
            auth.login(request, user)
            return redirect('/')
        else:
            messages.info(request, 'Credentials Invalid')
            return redirect('login')
    
    return render(request, 'login.html')



def signup(request):
    if request.method == 'POST':
        email = request.POST['email']
        username = request.POST['username']
        password = request.POST['password']
        password2 = request.POST['password2']

        if password == password2:
            if User.objects.filter(email=email).exists():
                messages.info(request, 'Email Taken')
                return redirect('signup')
            elif User.objects.filter(username=username).exists():
                messages.info(request, 'Username Taken')
                return redirect('signup')
            else:
                user = User.objects.create_user(username=username, email=email, password=password)
                user.save()

                # log user in
                user_login = auth.authenticate(username=username, password=password)
                auth.login(request, user_login)
                return redirect('/')
        else:
            messages.info(request, 'Password Not Matching')
            return redirect('signup')
    else:
        return render(request, 'signup.html')




@login_required(login_url='login')
def my_list(request):

    movie_list = MovieList.objects.filter(owner_user=request.user)
    user_movie_list = []

    for movie in movie_list:
        user_movie_list.append(movie.movie)

    context = {
        'movies': user_movie_list
    }
    return render(request, 'my_list.html', context)




@login_required(login_url='login')
def add_to_list(request):
    if request.method == 'POST':
        movie_url_id = request.POST.get('movie_id')
        uuid_pattern = r'[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}'
        match = re.search(uuid_pattern, movie_url_id)
        movie_id = match.group() if match else None

        movie = get_object_or_404(Movie, uu_id=movie_id)
        movie_list, created = MovieList.objects.get_or_create(owner_user=request.user, movie=movie)

        if created:
            response_data = {'status': 'success', 'message': 'Added ✓'}
        else:
            response_data = {'status': 'info', 'message': 'Movie already in list'}

        return JsonResponse(response_data)
    else:
        # return error
        return JsonResponse({'status': 'error', 'message': 'Invalid request'}, status=400)




@login_required(login_url='login')
def logout(request):
    auth.logout(request)
    return redirect('login')

templates/genre.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Netflix Clone</title>
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'assets/style.css' %}" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
   
</head>

<body class="text-white" style="background-color: #141414;">
    <header class="p-5 flex justify-between items-center">
        <img src="https://upload.wikimedia.org/wikipedia/commons/7/7a/Logonetflix.png" height="30" alt="Netflix Logo" width="110">
        
        
        <nav class="flex space-x-5">
            <span><a href="/">Home</a></span>
            
            <div class="dropdown">
                <span id="dropdownMenuButton" class="cursor-pointer">Genres ▼</span>
                
                <div id="dropdownMenu" class="dropdown-content hidden">
                    <ul><a href="/genre/action/">Action</a></ul>
                    <ul><a href="/genre/comedy/">Comedy</a></ul>
                    <ul><a href="/genre/drama/">Drama</a></ul>
                    <ul><a href="/genre/horror/">Horror</a></ul>
                    <ul><a href="/genre/romance/">Romance</a></ul>
                    <ul><a href="/genre/sciencefiction/">Science Fiction</a></ul>
                    <ul><a href="/genre/fantasy/">Fantasy</a></ul>
                </div>
            </div>

            <span><a href="/my-list">My List</a></span>
        </nav>


        <div class="flex space-x-5 items-center">
            <form action="search" method="POST">
                {% csrf_token %}
                <input type="search" name="search_term" placeholder="Search" class="bg-gray-700 p-2 rounded">
                <button class="bg-red-600 text-white p-2 rounded hover:bg-red-500">Search</button>
            </form>
            <div class="relative">
                <a href="#" class="block p-2">Welcome, {{user.username}}</a>
                <a href="/logout" class="block p-2">Logout</a>
            </div>
        </div>
    </header>
    
    <hr>

    <section class="py-10 px-5">
    
        <div align="center">
            <h2 class="text-xl mb-5">
                '{{movie_genre | title}}' Films
            </h2>
        </div>
        <div class="flex space-x-5 overflow-x-auto">

            {% for movie in movies %}
            <div class="w-40 h-64 flex-shrink-0 film-card"
                onclick="showModal(this)" 
                data-title="{{ movie.title }}"
                data-description="{{ movie.description }}"
                data-release-date="{{ movie.release_date|date:'Y' }}"
                data-genre="{{ movie.get_genre_display }}" 
                data-length="{{ movie.length }}"
                data-image-card-url="{{ movie.image_card.url }}"
                data-image-cover-url="{{ movie.image_cover.url }}"
                data-video-url="/movie/{{ movie.uu_id }}"
                style="background-image: url('{{movie.image_card.url}}'); background-size: cover; background-position: center;">
            </div>
            {% endfor %}
    </section>
    
   

    <!-- Modal -->
    <div class="modal" id="movieModal">
        <div class="modal-content">
            <div class="flex justify-between">
                <h2 class="text-xl mb-5">Movie Title</h2>
                <button onclick="hideModal()">X</button>
            </div>
            <img width="1000" height="100" src="https://bloximages.newyork1.vip.townnews.com/newsrecord.org/content/tncms/assets/v3/editorial/8/1e/81ea500c-45ac-11ee-a11e-a7402910a7e7/64ecaae69243a.image.jpg" alt="Movie Image" class=" mb-5">
            <div class="flex justify-between mb-5">
                <span>Year: 2023</span>
                <span>Length: 2h 15min</span>
            </div>
            <p class="mb-5">Detailed information about the movie.</p>
            <div class="flex space-x-4 mb-5">
                <a href="movie.html">
                    <button class="bg-red-600 text-white p-2 px-5 rounded hover:bg-red-500">Play</button>
                </a>
                <button id="addToListButton" onclick="addItemToList()" class="border border-white text-white p-2 px-5 rounded hover:bg-gray-700">
                    Add to List
                </button>
            </div>
        </div>
    </div>

    <script>
        function showModal(element) {
            // Retrieve data attributes
            const title = element.getAttribute('data-title');
            const description = element.getAttribute('data-description');
            const releaseDate = element.getAttribute('data-release-date');
            const genre = element.getAttribute('data-genre');
            const length = element.getAttribute('data-length');
            const imageCardUrl = element.getAttribute('data-image-card-url');
            const imageCoverUrl = element.getAttribute('data-image-cover-url');
            const dataVideoUrl = element.getAttribute('data-video-url');
        
            // Update the modal's content with the movie details
            const modal = document.getElementById('movieModal');
            modal.querySelector('.modal-content h2').textContent = title;
            modal.querySelector('.modal-content img').src = imageCoverUrl;
            modal.querySelector('.modal-content a').href = dataVideoUrl;  
            modal.querySelector('.modal-content img').alt = title + " Cover Image";
            modal.querySelector('.modal-content .flex span:first-child').textContent = "Year: " + releaseDate;
            modal.querySelector('.modal-content .flex span:nth-child(2)').textContent = "Genre: " + genre;
            modal.querySelector('.modal-content .flex span:last-child').textContent = "Length: " + length + "min";
            modal.querySelector('.modal-content p').textContent = description;
        
            // Show the modal
            modal.style.display = 'block';
            setTimeout(() => {
                modal.classList.add('modal-show');
            }, 50);
        }
        
        function hideModal() {
            const modal = document.querySelector('.modal');
            modal.classList.remove('modal-show');
            setTimeout(() => {
                modal.style.display = 'none';
            }, 300);
        }
        

        window.onclick = function(event) {
            if (event.target === document.getElementById('movieModal')) {
                hideModal();
            }
        }

        function addItemToList() {
            const modal = document.getElementById('movieModal')
            var movieID = modal.querySelector('.modal-content a').href;

            $.ajax({
                url: "{% url 'add-to-list' %}",
                type: "POST",
                data: {
                    movie_id: movieID,
                    csrfmiddlewaretoken: "{{ csrf_token }}"
                },
                success: function(data) {
                    $('#addToListButton').text(data.message);

                    $('#addToListButton').prop('disabled', true);

                    console.log("Item added to list!");
                },
                error: function(xhr, errmsg, err) {
                    
                    console.error("Error adding item to list: " + errmsg);
                }
            });
        }
    </script>
</body>

</html>

templates/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Netflix Clone</title>
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'assets/style.css' %}" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
   
</head>

<body class="text-white" style="background-color: #141414;">
    <header class="p-5 flex justify-between items-center">
        <img src="https://upload.wikimedia.org/wikipedia/commons/7/7a/Logonetflix.png" height="30" alt="Netflix Logo" width="110">
        
        
        <nav class="flex space-x-5">
            <span><a href="{% url 'index' %}">Home</a></span>
            
            <div class="dropdown">
                <span id="dropdownMenuButton" class="cursor-pointer">Genres ▼</span>
                
                <div id="dropdownMenu" class="dropdown-content hidden">
                    <ul><a href="/genre/action/">Action</a></ul>
                    <ul><a href="/genre/comedy/">Comedy</a></ul>
                    <ul><a href="/genre/drama/">Drama</a></ul>
                    <ul><a href="/genre/horror/">Horror</a></ul>
                    <ul><a href="/genre/romance/">Romance</a></ul>
                    <ul><a href="/genre/sciencefiction/">Science Fiction</a></ul>
                    <ul><a href="/genre/fantasy/">Fantasy</a></ul>
                </div>
            </div>

            <span><a href="/my-list">My List</a></span>
        </nav>


        <div class="flex space-x-5 items-center">
            <form action="search" method="POST">
                {% csrf_token %}
                <input type="search" name="search_term" placeholder="Search" class="bg-gray-700 p-2 rounded">
                <button class="bg-red-600 text-white p-2 rounded hover:bg-red-500">Search</button>
            </form>
            <div class="relative">
                 <a href="{% url 'index' %}" class="block p-2">Welcome, {{user.username}}</a>
                <a href="{% url 'logout' %}" class="block p-2">Logout</a>
            </div>
        </div>
    </header>
    <section class="relative py-20 px-10" style="background-image: url('{{featured_movie.image_cover.url}}'); background-size: cover; background-position: center;">
        <div>
            <h1 style="color: black;" class="text-5xl mb-5">{{featured_movie.title}}</h1>
            <p style="color: black;" class="mb-5">{{featured_movie.description}}</p>
            <div class="flex space-x-4">
                <a href="/movie/{{featured_movie.uu_id}}">
                    <button class="bg-red-600 text-white p-2 px-5 rounded hover:bg-red-500">Play</button>
                </a>
            </div>
        </div>
    </section>
    <section class="py-10 px-5">
    
        <h2 class="text-xl mb-5">Popular on Netflix</h2>
        <div class="flex space-x-5 overflow-x-auto">

            {% for movie in movies %}
            <div class="w-40 h-64 flex-shrink-0 film-card"
                onclick="showModal(this)" 
                data-title="{{ movie.title }}"
                data-description="{{ movie.description }}"
                data-release-date="{{ movie.release_date|date:'Y' }}"
                data-genre="{{ movie.get_genre_display }}" 
                data-length="{{ movie.length }}"
                data-image-card-url="{{ movie.image_card.url }}"
                data-image-cover-url="{{ movie.image_cover.url }}"
                data-video-url="/movie/{{ movie.uu_id }}"
                style="background-image: url('{{movie.image_card.url}}'); background-size: cover; background-position: center;">
            </div>
            {% endfor %}
    </section>
    
    

    <!-- Modal -->
    <div class="modal" id="movieModal">
        <div class="modal-content">
            <div class="flex justify-between">
                <h2 class="text-xl mb-5">Movie Title</h2>
                <button onclick="hideModal()">X</button>
            </div>
            <img width="1000" height="100" src="https://bloximages.newyork1.vip.townnews.com/newsrecord.org/content/tncms/assets/v3/editorial/8/1e/81ea500c-45ac-11ee-a11e-a7402910a7e7/64ecaae69243a.image.jpg" alt="Movie Image" class=" mb-5">
            <div class="flex justify-between mb-5">
                <span>Year: 2023</span>
                <span>Length: 2h 15min</span>
            </div>
            <p class="mb-5">Detailed information about the movie.</p>
            <div class="flex space-x-4 mb-5">
                <a href="movie.html">
                    <button class="bg-red-600 text-white p-2 px-5 rounded hover:bg-red-500">Play</button>
                </a>
                <button id="addToListButton" onclick="addItemToList()" class="border border-white text-white p-2 px-5 rounded hover:bg-gray-700">
                    Add to List
                </button>
            </div>
            
        </div>
    </div>

    <script>
        function showModal(element) {
            // Retrieve data attributes
            const title = element.getAttribute('data-title');
            const description = element.getAttribute('data-description');
            const releaseDate = element.getAttribute('data-release-date');
            const genre = element.getAttribute('data-genre');
            const length = element.getAttribute('data-length');
            const imageCardUrl = element.getAttribute('data-image-card-url');
            const imageCoverUrl = element.getAttribute('data-image-cover-url');
            const dataVideoUrl = element.getAttribute('data-video-url');
        
            // Update the modal's content with the movie details
            const modal = document.getElementById('movieModal');
            modal.querySelector('.modal-content h2').textContent = title;
            modal.querySelector('.modal-content img').src = imageCoverUrl;
            modal.querySelector('.modal-content a').href = dataVideoUrl;  
            modal.querySelector('.modal-content img').alt = title + " Cover Image";
            modal.querySelector('.modal-content .flex span:first-child').textContent = "Year: " + releaseDate;
            modal.querySelector('.modal-content .flex span:nth-child(2)').textContent = "Genre: " + genre;
            modal.querySelector('.modal-content .flex span:last-child').textContent = "Length: " + length + "min";
            modal.querySelector('.modal-content p').textContent = description;
        
            // Show the modal
            modal.style.display = 'block';
            setTimeout(() => {
                modal.classList.add('modal-show');
            }, 50);
        }
        
        function hideModal() {
            const modal = document.querySelector('.modal');
            modal.classList.remove('modal-show');
            setTimeout(() => {
                modal.style.display = 'none';
            }, 300);
        }
        

        window.onclick = function(event) {
            if (event.target === document.getElementById('movieModal')) {
                hideModal();
            }
        }

        function addItemToList() {
            const modal = document.getElementById('movieModal')
            var movieID = modal.querySelector('.modal-content a').href;

            $.ajax({
               
                url: "{% url 'add-to-list' %}",
                type: "POST",
                data: {
                    movie_id: movieID,
                    csrfmiddlewaretoken: "{{ csrf_token }}"
                },
                success: function(data) {
                    $('#addToListButton').text(data.message);

                    $('#addToListButton').prop('disabled', true);

                    console.log("Item added to list!");
                },
                error: function(xhr, errmsg, err) {
                    
                    console.error("Error adding item to list: " + errmsg);
                }
            });
        }
    </script>
</body>

</html>

templates/login.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'assets/login.css' %}" />

    <title>Login</title>
</head>
<body>

    <div class="bg-image">
        <div class="signup-container">
            <h1>Login</h1>
            <h2>Unlimited movies, TV shows, and more.</h2>

            <div>
                <style>
                    h5{
                        color: red;
                    }
                </style>
                {% for message in messages %}
                <h5>{{message}}</h5>
                {% endfor %}
            </div>


            <form action="" method="POST">
                {% csrf_token %}
                <input type="text" name="username" placeholder="Username" />
                <input type="password" name="password" placeholder="Password" />
                <button style="color:white" type="submit" class="signup-btn">Login</button>
            </form>
            <div class="help-text" align="center">
                <span>Ready to watch? Enter your email to create or restart your membership.</span>
                <br>
                <br>
                <span>Dont have an account? <a href="{% url 'signup' %}">Signup</a></span>
            </div>
        </div>
    </div>

</body>
</html>

templates/my_list.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Netflix Clone</title>
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'assets/style.css' %}" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
   
</head>

<body class="text-white" style="background-color: #141414;">
    <header class="p-5 flex justify-between items-center">
        <img src="https://upload.wikimedia.org/wikipedia/commons/7/7a/Logonetflix.png" height="30" alt="Netflix Logo" width="110">
        
        
        <nav class="flex space-x-5">
            <span><a href="/">Home</a></span>
            
            <div class="dropdown">
                <span id="dropdownMenuButton" class="cursor-pointer">Genres ▼</span>
                
                <div id="dropdownMenu" class="dropdown-content hidden">
                    <ul><a href="/genre/action/">Action</a></ul>
                    <ul><a href="/genre/comedy/">Comedy</a></ul>
                    <ul><a href="/genre/drama/">Drama</a></ul>
                    <ul><a href="/genre/horror/">Horror</a></ul>
                    <ul><a href="/genre/romance/">Romance</a></ul>
                    <ul><a href="/genre/sciencefiction/">Science Fiction</a></ul>
                    <ul><a href="/genre/fantasy/">Fantasy</a></ul>
                </div>
            </div>

            <span><a href="/my-list">My List</a></span>
        </nav>


        <div class="flex space-x-5 items-center">
            <form action="search" method="POST">
                {% csrf_token %}
                <input type="search" name="search_term" placeholder="Search" class="bg-gray-700 p-2 rounded">
                <button class="bg-red-600 text-white p-2 rounded hover:bg-red-500">Search</button>
            </form>
            <div class="relative">
                <a href="#" class="block p-2">Welcome, {{user.username}}</a>
                <a href="/logout" class="block p-2">Logout</a>
            </div>
        </div>
    </header>
    
    <hr>

    <section class="py-10 px-5">
    
        <div align="center">
            <h2 class="text-xl mb-5">
                My List
            </h2>
        </div>
        <div class="flex space-x-5 overflow-x-auto">

            {% for movie in movies reversed %}
            <div class="w-40 h-64 flex-shrink-0 film-card"
                onclick="showModal(this)" 
                data-title="{{ movie.title }}"
                data-description="{{ movie.description }}"
                data-release-date="{{ movie.release_date|date:'Y' }}"
                data-genre="{{ movie.get_genre_display }}" 
                data-length="{{ movie.length }}"
                data-image-card-url="{{ movie.image_card.url }}"
                data-image-cover-url="{{ movie.image_cover.url }}"
                data-video-url="/movie/{{ movie.uu_id }}"
                style="background-image: url('{{movie.image_card.url}}'); background-size: cover; background-position: center;">
            </div>
            {% endfor %}
    </section>
    
   

    <!-- Modal -->
    <div class="modal" id="movieModal">
        <div class="modal-content">
            <div class="flex justify-between">
                <h2 class="text-xl mb-5">Movie Title</h2>
                <button onclick="hideModal()">X</button>
            </div>
            <img width="1000" height="100" src="https://bloximages.newyork1.vip.townnews.com/newsrecord.org/content/tncms/assets/v3/editorial/8/1e/81ea500c-45ac-11ee-a11e-a7402910a7e7/64ecaae69243a.image.jpg" alt="Movie Image" class=" mb-5">
            <div class="flex justify-between mb-5">
                <span>Year: 2023</span>
                <span>Length: 2h 15min</span>
            </div>
            <p class="mb-5">Detailed information about the movie.</p>
            <div class="flex space-x-4 mb-5">
                <a href="movie.html">
                    <button class="bg-red-600 text-white p-2 px-5 rounded hover:bg-red-500">Play</button>
                </a>
                <button id="addToListButton" onclick="addItemToList()" class="border border-white text-white p-2 px-5 rounded hover:bg-gray-700">
                    Add to List
                </button>
            </div>
        </div>
    </div>

    <script>
        function showModal(element) {
            // Retrieve data attributes
            const title = element.getAttribute('data-title');
            const description = element.getAttribute('data-description');
            const releaseDate = element.getAttribute('data-release-date');
            const genre = element.getAttribute('data-genre');
            const length = element.getAttribute('data-length');
            const imageCardUrl = element.getAttribute('data-image-card-url');
            const imageCoverUrl = element.getAttribute('data-image-cover-url');
            const dataVideoUrl = element.getAttribute('data-video-url');
        
            // Update the modal's content with the movie details
            const modal = document.getElementById('movieModal');
            modal.querySelector('.modal-content h2').textContent = title;
            modal.querySelector('.modal-content img').src = imageCoverUrl;
            modal.querySelector('.modal-content a').href = dataVideoUrl;  
            modal.querySelector('.modal-content img').alt = title + " Cover Image";
            modal.querySelector('.modal-content .flex span:first-child').textContent = "Year: " + releaseDate;
            modal.querySelector('.modal-content .flex span:nth-child(2)').textContent = "Genre: " + genre;
            modal.querySelector('.modal-content .flex span:last-child').textContent = "Length: " + length + "min";
            modal.querySelector('.modal-content p').textContent = description;
        
            // Show the modal
            modal.style.display = 'block';
            setTimeout(() => {
                modal.classList.add('modal-show');
            }, 50);
        }
        
        function hideModal() {
            const modal = document.querySelector('.modal');
            modal.classList.remove('modal-show');
            setTimeout(() => {
                modal.style.display = 'none';
            }, 300);
        }
        

        window.onclick = function(event) {
            if (event.target === document.getElementById('movieModal')) {
                hideModal();
            }
        }

        function addItemToList() {
            const modal = document.getElementById('movieModal')
            var movieID = modal.querySelector('.modal-content a').href;

            $.ajax({
                url: "{% url 'add-to-list' %}",
                type: "POST",
                data: {
                    movie_id: movieID,
                    csrfmiddlewaretoken: "{{ csrf_token }}"
                },
                success: function(data) {
                    $('#addToListButton').text(data.message);

                    $('#addToListButton').prop('disabled', true);

                    console.log("Item added to list!");
                },
                error: function(xhr, errmsg, err) {
                    
                    console.error("Error adding item to list: " + errmsg);
                }
            });
        }
    </script>
</body>

</html>